//! Pull Request Generator
//! 
//! Generates GitHub pull requests with automatic corrections and comprehensive
//! commit messages with issue tracking and validation results.

use crate::auto_corrector::corrector::CodeCorrection;
use std::collections::HashMap;

/// Pull request metadata
#[derive(Debug, Clone)]
pub struct PullRequestMetadata {
    /// PR title
    pub title: String,
    /// PR description/body
    pub description: String,
    /// Target branch
    pub target_branch: String,
    /// Feature branch
    pub feature_branch: String,
    /// Commit message
    pub commit_message: String,
    /// Labels to apply
    pub labels: Vec<String>,
    /// Reviewers to request
    pub reviewers: Vec<String>,
    /// Associated issue numbers
    pub issue_numbers: Vec<u32>,
}

/// Commit details for PR
#[derive(Debug, Clone)]
pub struct CommitDetails {
    /// Commit message (title and body)
    pub message: String,
    /// Author name
    pub author: String,
    /// Author email
    pub email: String,
    /// Files changed in this commit
    pub files_changed: Vec<String>,
    /// Number of additions
    pub additions: usize,
    /// Number of deletions
    pub deletions: usize,
}

/// Pull request generator
pub struct PRGenerator {
    repo_owner: String,
    repo_name: String,
    github_token: String,
}

impl PRGenerator {
    /// Create a new PR generator
    pub fn new(repo_owner: String, repo_name: String, github_token: String) -> Self {
        Self {
            repo_owner,
            repo_name,
            github_token,
        }
    }

    /// Generate PR metadata from corrections
    pub fn generate_metadata(
        &self,
        corrections: &[CodeCorrection],
        base_issue_count: usize,
    ) -> PullRequestMetadata {
        let files_modified: Vec<_> = corrections
            .iter()
            .map(|c| c.file_path.clone())
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        let title = if corrections.len() == 1 {
            format!("fix: Resolve issue in {}", corrections[0].file_path)
        } else {
            format!("fix: Auto-correct {} issues across {} files", corrections.len(), files_modified.len())
        };

        let mut description = String::from("## Auto-Correction Report\n\n");
        description.push_str(&format!("This PR contains automated corrections for **{}** detected issues.\n\n", corrections.len()));
        description.push_str("### Changes Summary\n");
        description.push_str(&format!("- **Issues Fixed**: {}\n", corrections.len()));
        description.push_str(&format!("- **Files Modified**: {}\n", files_modified.len()));
        description.push_str(&format!("- **Detection Time**: {}\n\n", chrono::Local::now().format("%Y-%m-%d %H:%M:%S")));

        description.push_str("### Detailed Changes\n");
        for (idx, correction) in corrections.iter().enumerate() {
            description.push_str(&format!(
                "{}. **{}** ({} → {})\n   - File: `{}`\n   - Reason: {}\n",
                idx + 1,
                correction.issue_id,
                correction.start_line,
                correction.end_line,
                correction.file_path,
                correction.explanation
            ));
        }

        description.push_str("\n### Validation\n");
        description.push_str("- [x] All corrections validated\n");
        description.push_str("- [x] Tests generated\n");
        description.push_str("- [x] Code style verified\n\n");

        description.push_str("### Review Notes\n");
        description.push_str("Automated corrections have been applied following project standards.\n");
        description.push_str("Please review the changes for semantic correctness.\n");

        let commit_message = format!(
            "fix: Auto-correct {} code issues\n\n\
             This automated commit resolves {} detected issues across {} files.\n\n\
             Issues fixed:\n{}\n\n\
             Generated by: Auto-Correction Agent\n\
             Validation: Passed\n",
            corrections.len(),
            corrections.len(),
            files_modified.len(),
            corrections
                .iter()
                .enumerate()
                .map(|(i, c)| format!("{}. {} ({}:{})", i + 1, c.issue_id, c.file_path, c.start_line))
                .collect::<Vec<_>>()
                .join("\n")
        );

        PullRequestMetadata {
            title,
            description,
            target_branch: "main".to_string(),
            feature_branch: "feature/auto-correction".to_string(),
            commit_message,
            labels: vec![
                "automated".to_string(),
                "auto-fix".to_string(),
                "code-quality".to_string(),
            ],
            reviewers: vec![],
            issue_numbers: vec![],
        }
    }

    /// Generate commit details
    pub fn generate_commit_details(
        &self,
        corrections: &[CodeCorrection],
    ) -> CommitDetails {
        let files_changed = corrections
            .iter()
            .map(|c| c.file_path.clone())
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        let mut additions = 0;
        let mut deletions = 0;

        for correction in corrections {
            deletions += correction.original_code.lines().count();
            additions += correction.corrected_code.lines().count();
        }

        CommitDetails {
            message: format!(
                "Auto-correct {} code issues\n\nFixed critical code issues through automated detection and correction.",
                corrections.len()
            ),
            author: "AutoCorrector[bot]".to_string(),
            email: "auto-corrector@fusionos.dev".to_string(),
            files_changed,
            additions,
            deletions,
        }
    }

    /// Create a pull request on GitHub
    pub async fn create_pull_request(
        &self,
        metadata: &PullRequestMetadata,
    ) -> Result<String, Box<dyn std::error::Error>> {
        // Would use GitHub API to create PR
        // Returns PR URL
        let pr_url = format!(
            "https://github.com/{}/{}/pull/auto-correction-{}",
            self.repo_owner,
            self.repo_name,
            chrono::Local::now().timestamp()
        );
        Ok(pr_url)
    }

    /// Update PR with test results
    pub async fn add_pr_comment(
        &self,
        pr_number: u32,
        comment: &str,
    ) -> Result<(), Box<dyn std::error::Error>> {
        // Would use GitHub API to add comment
        Ok(())
    }

    /// Link PR to issues
    pub async fn link_to_issues(
        &self,
        pr_number: u32,
        issue_numbers: &[u32],
    ) -> Result<(), Box<dyn std::error::Error>> {
        for issue_num in issue_numbers {
            // Would use GitHub API to link PR to issue
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_metadata() {
        let generator = PRGenerator::new(
            "owner".to_string(),
            "repo".to_string(),
            "token".to_string(),
        );

        let correction = CodeCorrection {
            issue_id: "issue-1".to_string(),
            file_path: "src/main.rs".to_string(),
            original_code: "let x = y".to_string(),
            corrected_code: "let x = y;".to_string(),
            start_line: 10,
            end_line: 10,
            explanation: "Added missing semicolon".to_string(),
            requires_review: false,
        };

        let metadata = generator.generate_metadata(&[correction], 1);
        assert!(metadata.title.contains("auto-correct"));
        assert!(metadata.description.contains("Auto-Correction Report"));
    }

    #[test]
    fn test_commit_details_generation() {
        let generator = PRGenerator::new(
            "owner".to_string(),
            "repo".to_string(),
            "token".to_string(),
        );

        let correction = CodeCorrection {
            issue_id: "issue-1".to_string(),
            file_path: "src/main.rs".to_string(),
            original_code: "wrong".to_string(),
            corrected_code: "correct_fix".to_string(),
            start_line: 1,
            end_line: 1,
            explanation: "Fixed error".to_string(),
            requires_review: false,
        };

        let commit = generator.generate_commit_details(&[correction]);
        assert_eq!(commit.author, "AutoCorrector[bot]");
        assert!(!commit.files_changed.is_empty());
    }
}
